# Required: A short name for the action package
name: GAM-Action-Pack

# Required: A description of what's in the action package.
description: Google Ad Manager API integration for fetching network information and managing reports

# Package version number, recommend using semver.org
version: 0.0.1

dependencies:
  conda-forge:
  - python=3.10.15
  - uv=0.4.17
  pypi:
  - sema4ai-actions=1.3.5
  - python-dotenv
  - google-ads=26.0.1
  - google-ads-admanager=0.2.5
  - google-auth-oauthlib=1.2.1
  - google-auth=2.35.0

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
  - ./.git/**
  - ./.vscode/**
  - ./devdata/**
  - ./output/**
  - ./venv/**
  - ./.venv/**
  - ./.DS_store/**
  - ./**/*.pyc
  - ./**/*.zip 